{% set version = "2.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-geigen
  version: {{ version|replace("-", "_") }}

source:
  fn: geigen_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/geigen_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geigen/geigen_{{ version }}.tar.gz
  sha256: c7ffb869afb8b439a8288addccaa645289b00b12a355f351572b5fc913278f2e

build:
  number: 8
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('geigen')"           # [not win]
    - "\"%R%\" -e \"library('geigen')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=geigen
  license: GPL-2.0-or-later
  summary: Functions to compute generalized eigenvalues and eigenvectors, the generalized Schur
    decomposition and the generalized Singular Value Decomposition of a matrix pair,
    using Lapack routines.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
