travis:
  secure:
    BINSTAR_TOKEN: dTfwj2QEFw7soiBQucDAejDWrWUQd0oTS/iJ0aeE6S+kHRMTSPAS/ma6VEk2h4euFtx9qdfO6SHw4OZcyM8Oowhph02FJrBLO/F2oB4rJx0+LbpEj/ItVTXLcB+uKyNd0CF+jbfuVVC/raxxfzw1AghISzMW/w/vkg6wJ/VUYril8locE0HhmxZ0w8QydyPBM8+5QGXO+wKZOaUlzHCr0vgR4UjUyOSQ1idavvzNlnXIdNrGapfMj7jFUaUc3jfX4TJTAFeHWtZQqLOfk+znXIXv3cSBiVwuJTOYmq/DzszLvCWIlgFzyS+T5RvJ3DRLvbfK+q7LwBL3clt1vkwQNEFt8TODw79FEcS4brJplE5S+PckeXszQsHw4m6vi+VPGtb6+oyRCm67SFK3w89CD2ycoBFsuiK0qs86VWJxJhurTthAlTGjt73+9dNAHseiV/QGhTf4m6/00u7wCximf3HOPu4VkzN4g8Tb267bn9nIG6hYXInefxsZRynxsjwWonrW52XJvNr4s9r9RQipFpNpRW9NpGhLlVtb95THGov+muT4q5GSOGiYeLOdP4IGGAjbG0vOWRaqLsEP+s6BP5SAinza69kP7MXbsgGB76Z121v4RYHwOMSQQtAlVqtTyA6CAKwe9uxWoDqVXar4TVJ1ilnr/YaKOvmTSf6wya0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
